# Generated by Django 4.2 on 2023-04-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chawo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.TextField(max_length=50)),
                ('ans', models.TextField(max_length=500)),
            ],
        ),
    ]
