# Generated by Django 4.2 on 2023-04-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chawo',
            name='quest',
            field=models.TextField(max_length=51),
        ),
    ]
